version: "3"

services:
  node:
    build: .
    restart: always
    user: "node"
    environment:
      - NODE_ENV=production
      - DEBUG=-info,error:*,-debug:*
    volumes:
       - ./:/usr/src/app
       - /usr/src/app/node_modules
